#pragma once

#define BOARD_PROFILE_ID "esp32-c3"
#define BOARD_PROFILE_DEVICE_NAME "pio-sensors-node-c3"

#define BOARD_PROFILE_ENABLE_DHT 1
#define BOARD_PROFILE_DHT_IS_DHT22 0
#define BOARD_PROFILE_DHT_PIN 1

#define BOARD_PROFILE_ENABLE_MMWAVE 1
#define BOARD_PROFILE_MMWAVE_UART_TX_PIN 3
#define BOARD_PROFILE_MMWAVE_UART_RX_PIN 4
#define BOARD_PROFILE_MMWAVE_UART_BAUDRATE 256000

#define BOARD_PROFILE_BATTERY_ADC_PIN 0
#define BOARD_PROFILE_BATTERY_CHARGE_PIN -1

#define BOARD_PROFILE_ENABLE_CAMERA 0
#define BOARD_PROFILE_CAMERA_PIN_D0 -1
#define BOARD_PROFILE_CAMERA_PIN_D1 -1
#define BOARD_PROFILE_CAMERA_PIN_D2 -1
#define BOARD_PROFILE_CAMERA_PIN_D3 -1
#define BOARD_PROFILE_CAMERA_PIN_D4 -1
#define BOARD_PROFILE_CAMERA_PIN_D5 -1
#define BOARD_PROFILE_CAMERA_PIN_D6 -1
#define BOARD_PROFILE_CAMERA_PIN_D7 -1
#define BOARD_PROFILE_CAMERA_PIN_XCLK -1
#define BOARD_PROFILE_CAMERA_PIN_PCLK -1
#define BOARD_PROFILE_CAMERA_PIN_VSYNC -1
#define BOARD_PROFILE_CAMERA_PIN_HREF -1
#define BOARD_PROFILE_CAMERA_PIN_SDA -1
#define BOARD_PROFILE_CAMERA_PIN_SCL -1
#define BOARD_PROFILE_CAMERA_PIN_RESET -1
#define BOARD_PROFILE_CAMERA_PIN_PWDN -1
