#pragma once

#define BOARD_PROFILE_ID "esp32-cam-ai-thinker"
#define BOARD_PROFILE_DEVICE_NAME "pio-sensors-node-cam"

#define BOARD_PROFILE_ENABLE_DHT 0
#define BOARD_PROFILE_DHT_IS_DHT22 0
#define BOARD_PROFILE_DHT_PIN -1

#define BOARD_PROFILE_ENABLE_MMWAVE 0
#define BOARD_PROFILE_MMWAVE_UART_TX_PIN -1
#define BOARD_PROFILE_MMWAVE_UART_RX_PIN -1
#define BOARD_PROFILE_MMWAVE_UART_BAUDRATE 256000

#define BOARD_PROFILE_BATTERY_ADC_PIN 33
#define BOARD_PROFILE_BATTERY_CHARGE_PIN -1

#define BOARD_PROFILE_ENABLE_CAMERA 1
#define BOARD_PROFILE_CAMERA_PIN_D0 5
#define BOARD_PROFILE_CAMERA_PIN_D1 18
#define BOARD_PROFILE_CAMERA_PIN_D2 19
#define BOARD_PROFILE_CAMERA_PIN_D3 21
#define BOARD_PROFILE_CAMERA_PIN_D4 36
#define BOARD_PROFILE_CAMERA_PIN_D5 39
#define BOARD_PROFILE_CAMERA_PIN_D6 34
#define BOARD_PROFILE_CAMERA_PIN_D7 35
#define BOARD_PROFILE_CAMERA_PIN_XCLK 0
#define BOARD_PROFILE_CAMERA_PIN_PCLK 22
#define BOARD_PROFILE_CAMERA_PIN_VSYNC 25
#define BOARD_PROFILE_CAMERA_PIN_HREF 23
#define BOARD_PROFILE_CAMERA_PIN_SDA 26
#define BOARD_PROFILE_CAMERA_PIN_SCL 27
#define BOARD_PROFILE_CAMERA_PIN_RESET -1
#define BOARD_PROFILE_CAMERA_PIN_PWDN 32
