#pragma once

#define BOARD_PROFILE_ID "esp32-s3"
#define BOARD_PROFILE_DEVICE_NAME "pio-sensors-node-s3"

#define BOARD_PROFILE_ENABLE_DHT 1
#define BOARD_PROFILE_DHT_IS_DHT22 0
#define BOARD_PROFILE_DHT_PIN 1

#define BOARD_PROFILE_ENABLE_MMWAVE 0
#define BOARD_PROFILE_MMWAVE_UART_TX_PIN -1
#define BOARD_PROFILE_MMWAVE_UART_RX_PIN -1
#define BOARD_PROFILE_MMWAVE_UART_BAUDRATE 256000

#define BOARD_PROFILE_BATTERY_ADC_PIN 0
#define BOARD_PROFILE_BATTERY_CHARGE_PIN -1
