#pragma once
#include "hw.h"

#define DEVICE_NAME BOARD_PROFILE_DEVICE_NAME
#define POWERSAVE_SLEEP_MODE_DEEP 1
#define POWERSAVE_SLEEP_MODE_LIGHT 2

#ifndef ENABLE_POWERSAVE
#define ENABLE_POWERSAVE 1
#endif
// Select sleep mode: POWERSAVE_SLEEP_MODE_DEEP or POWERSAVE_SLEEP_MODE_LIGHT
#ifndef POWERSAVE_SLEEP_MODE
#define POWERSAVE_SLEEP_MODE POWERSAVE_SLEEP_MODE_DEEP
#endif
// Deep sleep wake interval (default: 10 seconds)
#ifndef POWERSAVE_DEEP_SLEEP_SEC
#define POWERSAVE_DEEP_SLEEP_SEC 10
#endif
// Light sleep wake interval (default: 300 ms)
#ifndef POWERSAVE_LIGHT_SLEEP_MS
#define POWERSAVE_LIGHT_SLEEP_MS 300
#endif

#define DHT_SENSOR_ENABLED BOARD_PROFILE_ENABLE_DHT
#define DHT_SENSOR_IS_DHT22 BOARD_PROFILE_DHT_IS_DHT22
#define CAMERA_SENSOR_ENABLED BOARD_PROFILE_ENABLE_CAMERA
#ifndef DHT_READ_INTERVAL_MS
#define DHT_READ_INTERVAL_MS 5000
#endif

#define MMWAVE_SENSOR_ENABLED BOARD_PROFILE_ENABLE_MMWAVE
#define MMWAVE_UART_BAUDRATE BOARD_PROFILE_MMWAVE_UART_BAUDRATE
#ifndef MMWAVE_READ_INTERVAL_MS
#define MMWAVE_READ_INTERVAL_MS 3000
#endif
#ifndef MMWAVE_SAMPLE_WINDOW_MS
#define MMWAVE_SAMPLE_WINDOW_MS 1200
#endif
#ifndef MMWAVE_POLL_INTERVAL_MS
#define MMWAVE_POLL_INTERVAL_MS 20
#endif
#ifndef MMWAVE_FILTER_ENABLED
#define MMWAVE_FILTER_ENABLED 1
#endif
#ifndef MMWAVE_PRESENCE_ON_CONSECUTIVE
#define MMWAVE_PRESENCE_ON_CONSECUTIVE 2
#endif
#ifndef MMWAVE_PRESENCE_OFF_CONSECUTIVE
#define MMWAVE_PRESENCE_OFF_CONSECUTIVE 2
#endif
#ifndef MMWAVE_PRESENCE_OFF_HOLD_MS
#define MMWAVE_PRESENCE_OFF_HOLD_MS 5000
#endif
#ifndef MMWAVE_DISTANCE_MEDIAN_WINDOW
#define MMWAVE_DISTANCE_MEDIAN_WINDOW 5
#endif

#ifndef NODE_SEND_IDENTITY_STATE
#define NODE_SEND_IDENTITY_STATE 1
#endif
#ifndef NODE_MASTER_WAIT_TIMEOUT_MS
#define NODE_MASTER_WAIT_TIMEOUT_MS 5000
#endif
#ifndef NODE_MASTER_POLL_INTERVAL_MS
#define NODE_MASTER_POLL_INTERVAL_MS 50
#endif
#ifndef NODE_DHT_RETRY_DELAY_MS
#define NODE_DHT_RETRY_DELAY_MS 1200
#endif
#ifndef NODE_POST_SEND_SETTLE_MS
#define NODE_POST_SEND_SETTLE_MS 120
#endif

#ifndef ENABLE_WIFI_MODE
#define ENABLE_WIFI_MODE 0
#endif
#ifndef WIFI_CONNECT_TIMEOUT_MS
#define WIFI_CONNECT_TIMEOUT_MS 15000
#endif
#ifndef WIFI_CLIENT_HOSTNAME
#define WIFI_CLIENT_HOSTNAME DEVICE_NAME
#endif

#ifndef ENABLE_WEBSOCKET_GATEWAY
#define ENABLE_WEBSOCKET_GATEWAY 1
#endif
#ifndef WEBSOCKET_SERVER_PORT
#define WEBSOCKET_SERVER_PORT 81
#endif
#ifndef WEBSOCKET_MAX_HOOKS
#define WEBSOCKET_MAX_HOOKS 8
#endif
#ifndef WEBSOCKET_CAMERA_DEFAULT_WIDTH
#define WEBSOCKET_CAMERA_DEFAULT_WIDTH 320
#endif
#ifndef WEBSOCKET_CAMERA_DEFAULT_HEIGHT
#define WEBSOCKET_CAMERA_DEFAULT_HEIGHT 240
#endif
#ifndef WEBSOCKET_CAMERA_DEFAULT_FORMAT
#define WEBSOCKET_CAMERA_DEFAULT_FORMAT "jpg"
#endif
#ifndef WEBSOCKET_CAMERA_XCLK_HZ
#define WEBSOCKET_CAMERA_XCLK_HZ 20000000
#endif
#ifndef WEBSOCKET_CAMERA_JPEG_QUALITY
#define WEBSOCKET_CAMERA_JPEG_QUALITY 12
#endif
#ifndef WEBSOCKET_CAMERA_FB_COUNT
#define WEBSOCKET_CAMERA_FB_COUNT 2
#endif
#ifndef WEBSOCKET_STREAM_MAX_CLIENTS
#define WEBSOCKET_STREAM_MAX_CLIENTS 4
#endif
#ifndef WEBSOCKET_STREAM_DEFAULT_INTERVAL_MS
#define WEBSOCKET_STREAM_DEFAULT_INTERVAL_MS 500
#endif
#ifndef WEBSOCKET_STREAM_MIN_INTERVAL_MS
#define WEBSOCKET_STREAM_MIN_INTERVAL_MS 120
#endif

#ifndef BATTERY_FILTER_ENABLED
#define BATTERY_FILTER_ENABLED 1
#endif
#ifndef BATTERY_ADC_SAMPLES
#define BATTERY_ADC_SAMPLES 15
#endif
#ifndef BATTERY_ADC_TRIM_PERCENT
#define BATTERY_ADC_TRIM_PERCENT 20
#endif
#ifndef BATTERY_VOLTAGE_EMA_ALPHA
#define BATTERY_VOLTAGE_EMA_ALPHA 0.25f
#endif
