#pragma once
#include "hw.h"

#ifndef BOARD_PROFILE_ENABLE_SERVO
#define BOARD_PROFILE_ENABLE_SERVO 0
#endif
#ifndef BOARD_PROFILE_SERVO_GROUP_NAME
#define BOARD_PROFILE_SERVO_GROUP_NAME "servo_pair"
#endif
#ifndef BOARD_PROFILE_SERVO_GROUP_CHANNEL_COUNT
#define BOARD_PROFILE_SERVO_GROUP_CHANNEL_COUNT 2
#endif

#define DEVICE_NAME BOARD_PROFILE_DEVICE_NAME
#define POWERSAVE_SLEEP_MODE_DEEP 1
#define POWERSAVE_SLEEP_MODE_LIGHT 2

#ifndef ENABLE_POWERSAVE
#define ENABLE_POWERSAVE 1
#endif
// Select sleep mode: POWERSAVE_SLEEP_MODE_DEEP or POWERSAVE_SLEEP_MODE_LIGHT
#ifndef POWERSAVE_SLEEP_MODE
#define POWERSAVE_SLEEP_MODE POWERSAVE_SLEEP_MODE_LIGHT
#endif
#ifndef NODE_FORCE_ROLE_SLEEP_POLICY
#define NODE_FORCE_ROLE_SLEEP_POLICY 1
#endif
// Deep sleep wake interval (default: 10 seconds)
#ifndef POWERSAVE_DEEP_SLEEP_SEC
#define POWERSAVE_DEEP_SLEEP_SEC 10
#endif
// Light sleep wake interval (default: 300 ms)
#ifndef POWERSAVE_LIGHT_SLEEP_MS
#define POWERSAVE_LIGHT_SLEEP_MS 300
#endif

#define DHT_SENSOR_ENABLED BOARD_PROFILE_ENABLE_DHT
#define DHT_SENSOR_IS_DHT22 BOARD_PROFILE_DHT_IS_DHT22
#define CAMERA_SENSOR_ENABLED BOARD_PROFILE_ENABLE_CAMERA
#define SERVO_OUTPUT_ENABLED BOARD_PROFILE_ENABLE_SERVO

#if NODE_FORCE_ROLE_SLEEP_POLICY
#if (SERVO_OUTPUT_ENABLED || CAMERA_SENSOR_ENABLED)
#define NODE_EFFECTIVE_SLEEP_MODE POWERSAVE_SLEEP_MODE_LIGHT
#else
#define NODE_EFFECTIVE_SLEEP_MODE POWERSAVE_SLEEP_MODE_DEEP
#endif
#else
#define NODE_EFFECTIVE_SLEEP_MODE POWERSAVE_SLEEP_MODE
#endif

#ifndef DHT_READ_INTERVAL_MS
#define DHT_READ_INTERVAL_MS 5000
#endif

#define MMWAVE_SENSOR_ENABLED BOARD_PROFILE_ENABLE_MMWAVE
#define MMWAVE_UART_BAUDRATE BOARD_PROFILE_MMWAVE_UART_BAUDRATE
#ifndef MMWAVE_READ_INTERVAL_MS
#define MMWAVE_READ_INTERVAL_MS 3000
#endif
#ifndef MMWAVE_SAMPLE_WINDOW_MS
#define MMWAVE_SAMPLE_WINDOW_MS 1200
#endif
#ifndef MMWAVE_POLL_INTERVAL_MS
#define MMWAVE_POLL_INTERVAL_MS 20
#endif
#ifndef MMWAVE_FILTER_ENABLED
#define MMWAVE_FILTER_ENABLED 1
#endif
#ifndef MMWAVE_PRESENCE_ON_CONSECUTIVE
#define MMWAVE_PRESENCE_ON_CONSECUTIVE 2
#endif
#ifndef MMWAVE_PRESENCE_OFF_CONSECUTIVE
#define MMWAVE_PRESENCE_OFF_CONSECUTIVE 2
#endif
#ifndef MMWAVE_PRESENCE_OFF_HOLD_MS
#define MMWAVE_PRESENCE_OFF_HOLD_MS 5000
#endif
#ifndef MMWAVE_DISTANCE_MEDIAN_WINDOW
#define MMWAVE_DISTANCE_MEDIAN_WINDOW 5
#endif

#ifndef SERVO_GROUP_NAME
#define SERVO_GROUP_NAME BOARD_PROFILE_SERVO_GROUP_NAME
#endif
#ifndef SERVO_GROUP_CHANNEL_COUNT
#define SERVO_GROUP_CHANNEL_COUNT BOARD_PROFILE_SERVO_GROUP_CHANNEL_COUNT
#endif
#ifndef SERVO_MIN_DEG10
#define SERVO_MIN_DEG10 0
#endif
#ifndef SERVO_MAX_DEG10
#define SERVO_MAX_DEG10 1800
#endif
#ifndef SERVO_DEFAULT_DEG10
#define SERVO_DEFAULT_DEG10 900
#endif

#ifndef NODE_SEND_IDENTITY_STATE
#define NODE_SEND_IDENTITY_STATE 1
#endif
#ifndef NODE_MASTER_WAIT_TIMEOUT_MS
#define NODE_MASTER_WAIT_TIMEOUT_MS 22000
#endif
#ifndef NODE_MASTER_POLL_INTERVAL_MS
#define NODE_MASTER_POLL_INTERVAL_MS 50
#endif
#ifndef NODE_SCAN_CHANNEL_DWELL_MS
#define NODE_SCAN_CHANNEL_DWELL_MS 1500
#endif
#ifndef NODE_MASTER_CACHE_MAX_ENTRIES
#define NODE_MASTER_CACHE_MAX_ENTRIES 4
#endif
#ifndef NODE_MASTER_CACHE_FULLSCAN_TTL_MS
#define NODE_MASTER_CACHE_FULLSCAN_TTL_MS 30000
#endif
#ifndef NODE_MASTER_CACHE_FAST_SCAN_MAX_HOPS
#define NODE_MASTER_CACHE_FAST_SCAN_MAX_HOPS 6
#endif
#ifndef NODE_MASTER_CACHE_INVALID_AFTER_WAKE_MISS
#define NODE_MASTER_CACHE_INVALID_AFTER_WAKE_MISS 5
#endif
#ifndef NODE_SLEEP_IDLE_THRESHOLD_MS
#define NODE_SLEEP_IDLE_THRESHOLD_MS 5000
#endif
#ifndef NODE_DHT_RETRY_DELAY_MS
#define NODE_DHT_RETRY_DELAY_MS 1200
#endif
#ifndef NODE_POST_SEND_SETTLE_MS
#define NODE_POST_SEND_SETTLE_MS 120
#endif
#ifndef NODE_BOOT_ANNOUNCE_REPEATS
#define NODE_BOOT_ANNOUNCE_REPEATS 3
#endif
#ifndef NODE_BOOT_ANNOUNCE_GAP_MS
#define NODE_BOOT_ANNOUNCE_GAP_MS 40
#endif
#ifndef NODE_BOOT_SAMPLE_REPEATS
#define NODE_BOOT_SAMPLE_REPEATS 2
#endif
#ifndef NODE_TX_JITTER_MAX_MS
#define NODE_TX_JITTER_MAX_MS 25
#endif
#ifndef NODE_MASTER_POLL_JITTER_MAX_MS
#define NODE_MASTER_POLL_JITTER_MAX_MS 15
#endif
#ifndef NODE_STATE_BROADCAST_MIRROR
#define NODE_STATE_BROADCAST_MIRROR 1
#endif
#ifndef NODE_ESPNOW_SET_PEER_RATE
#define NODE_ESPNOW_SET_PEER_RATE 1
#endif
#ifndef NODE_ESPNOW_PEER_PHY_MODE
#define NODE_ESPNOW_PEER_PHY_MODE WIFI_PHY_MODE_11B
#endif
#ifndef NODE_ESPNOW_PEER_PHY_RATE
#define NODE_ESPNOW_PEER_PHY_RATE WIFI_PHY_RATE_1M_L
#endif
#ifndef NODE_ESPNOW_PEER_RATE_ERSU
#define NODE_ESPNOW_PEER_RATE_ERSU 0
#endif
#ifndef NODE_ESPNOW_PEER_RATE_DCM
#define NODE_ESPNOW_PEER_RATE_DCM 0
#endif
#ifndef NODE_ESPNOW_NO_MEM_BACKOFF_MS
#define NODE_ESPNOW_NO_MEM_BACKOFF_MS 80
#endif
#ifndef NODE_ESPNOW_NO_MEM_BACKOFF_JITTER_MS
#define NODE_ESPNOW_NO_MEM_BACKOFF_JITTER_MS 40
#endif
#ifndef NODE_ESPNOW_NO_MEM_LOG_GAP_MS
#define NODE_ESPNOW_NO_MEM_LOG_GAP_MS 500
#endif

#ifndef ENABLE_WIFI_MODE
#define ENABLE_WIFI_MODE 0
#endif
#ifndef WIFI_CONNECT_TIMEOUT_MS
#define WIFI_CONNECT_TIMEOUT_MS 15000
#endif
#ifndef WIFI_CLIENT_HOSTNAME
#define WIFI_CLIENT_HOSTNAME DEVICE_NAME
#endif

#ifndef ENABLE_WEBSOCKET_GATEWAY
#define ENABLE_WEBSOCKET_GATEWAY 1
#endif
#ifndef WEBSOCKET_SERVER_PORT
#define WEBSOCKET_SERVER_PORT 81
#endif
#ifndef WEBSOCKET_MAX_HOOKS
#define WEBSOCKET_MAX_HOOKS 8
#endif
#ifndef WEBSOCKET_CAMERA_DEFAULT_WIDTH
#define WEBSOCKET_CAMERA_DEFAULT_WIDTH 320
#endif
#ifndef WEBSOCKET_CAMERA_DEFAULT_HEIGHT
#define WEBSOCKET_CAMERA_DEFAULT_HEIGHT 240
#endif
#ifndef WEBSOCKET_CAMERA_DEFAULT_FORMAT
#define WEBSOCKET_CAMERA_DEFAULT_FORMAT "jpg"
#endif
#ifndef WEBSOCKET_CAMERA_XCLK_HZ
#define WEBSOCKET_CAMERA_XCLK_HZ 20000000
#endif
#ifndef WEBSOCKET_CAMERA_JPEG_QUALITY
#define WEBSOCKET_CAMERA_JPEG_QUALITY 12
#endif
#ifndef WEBSOCKET_CAMERA_FB_COUNT
#define WEBSOCKET_CAMERA_FB_COUNT 2
#endif
#ifndef WEBSOCKET_STREAM_MAX_CLIENTS
#define WEBSOCKET_STREAM_MAX_CLIENTS 4
#endif
#ifndef WEBSOCKET_STREAM_DEFAULT_INTERVAL_MS
#define WEBSOCKET_STREAM_DEFAULT_INTERVAL_MS 500
#endif
#ifndef WEBSOCKET_STREAM_MIN_INTERVAL_MS
#define WEBSOCKET_STREAM_MIN_INTERVAL_MS 120
#endif

#ifndef CAMERA_META_CAPTURE_RETRIES
#define CAMERA_META_CAPTURE_RETRIES 3
#endif
#ifndef CAMERA_META_RETRY_DELAY_MS
#define CAMERA_META_RETRY_DELAY_MS 25
#endif

#ifndef BATTERY_FILTER_ENABLED
#define BATTERY_FILTER_ENABLED 1
#endif
#ifndef BATTERY_ADC_SAMPLES
#define BATTERY_ADC_SAMPLES 15
#endif
#ifndef BATTERY_ADC_TRIM_PERCENT
#define BATTERY_ADC_TRIM_PERCENT 20
#endif
#ifndef BATTERY_VOLTAGE_EMA_ALPHA
#define BATTERY_VOLTAGE_EMA_ALPHA 0.25f
#endif
